CREATE DATABASE ERICKPRUEBA

USE ERICKPRUEBA 
GO

CREATE TABLE Persona (
	ID INT PRIMARY KEY IDENTITY (1,1),
	Nombre VARCHAR (60),
	FechaDeNacimiento DATETIME NOT NULL 
	)

SELECT * FROM Persona

INSERT Persona(Nombre, FechaDeNacimiento)  
    VALUES ('Prueba1', '2018/12/02')  
GO 

SET LANGUAGE SPANISH
SET DATEFORMAT dmy;  
GO  
